---
version: "3.3"

services:
  app:
    image: finalproject:tests
    container_name: digitalization-app
    depends_on:
      - tests
    links:
      - tests
    restart: always
    working_dir: /app
    volumes:
      - ./out:/app/out
      - ./lib:/app/lib
    command: [ "app.main.Main" ]

  tests:
    #image: andresgalvan/finalproject:tests
    container_name: digitalization-tests
    build:
      context: ./
      dockerfile: Dockerfile
    image: finalproject:tests
    command: [ "org.junit.runner.JUnitCore", "test.TestSuite" ]

