---
version: "3"

services:
  app:
    image: openjdk:8-jre-alpine
    container_name: app
    depends_on:
      - tests
    links:
      - tests
    restart: always
    working_dir: /usr/
    volumes:
      - ./out:/usr/out
      - ./lib:/usr/lib
    entrypoint: [ "java", "-cp", "out/production/FinalProject/:lib/jackson-annotations-2.12.2.jar:lib/jackson-core-2.12.2.jar:lib/jackson-databind-2.12.2.jar:lib/sqlite-jdbc-3.32.3.2.jar", "app.main.Main" ]

  tests:
    container_name: tests
    build:
      context: ./
      dockerfile: build.dockerfile
