---
version: "3"

services:
  java:
    container_name: java_app
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: main.dockerfile

  kotlin:
    container_name: tests
    build:
      context: ./
      dockerfile: tests.dockerfile
