
# name: Java CI with Gradle

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - name: set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
#       - name: Cache Gradle packages
#         uses: actions/cache@v2
#         with:
#           path: |
#             ~/.gradle/caches
#             ~/.gradle/wrapper
#           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#           restore-keys: |
#             ${{ runner.os }}-gradle-
#       - name: Build with Gradle
#         run.sh: ./gradlew build

#   tests:
#     needs: build
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - name: Run tests
#         run.sh: ./gradlew test
#       - name: Cleanup Gradle Cache
#         # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
#         # Restoring these files from a GitHub Actions cache might cause problems for future builds.
#         run.sh: |
#           rm -f ~/.gradle/caches/modules-2/modules-2.lock
            # This workflow will build a Java project with Gradle
#           rm -f ~/.gradle/caches/modules-2/gc.properties

